### ISSUE TITLE
Breaker.int - Off-Design Calculations

### ISSUE THREAD

**Issue by MoGeK** [nasa/NPSS-Power-System-Library#18] opened 2020-07-10 11:06 UTC
Hey everyone,

I am a student at the Technical University of Munich (TUM) and currently working on my master's thesis. As part of my thesis, my task is to build a NPSS hybrid-electric engine model. I have therefore been looking through and learning from your Power Systems Library quite a lot.
During some test runs with your baseline models I have run into an observation concerning the Breaker.int file:
In the first off-design case (case 1) of your baseline_tubroelectric.mdl and baseline_tubroelectric.run it seems like the breaker has significantly less losses although the flight/input conditions are still the same as in the on-design. This of course influences all other components as well (e.g. the power of the generator).
I therefore was wondering what could lead to this and took a closer look at the breaker file. In the breaker calculations the code naturally differentiates between on- and off-design. At the end of the on-design query the current (_I_) is being scaled (_I.scale(1./3.)_) for AC3. In off-design however the current is not being scaled at all. I therefore went ahead and adapted the off-design query to scale the current as well by adding the following code after line 348 to scale the current:
_if (EP_I.ElectricPowerType == "AC") {
} else if (EP_I.ElectricPowerType == "AC3") {
     I.scale(1. / 3.);
}_
After this adjustment, the breaker losses fit perfectly, and the power values of all components seemed to normalize.
I am still quite new to github  and power electronics and might be way off with my assumptions concerning this topic. If this is the case, I would be very happy to learn why my adjustment is not correct or off track!
I would be very happy to hear from you. Thanks so much!

Best regards,
Moritz (MoGeK)

**Comment by georgelthomas** [comment] 2020-08-04 20:03
Thanks for the feedback Moritz!

You have identified a valid issue. I started to look into this a few weeks ago. I thought I would have a chance to get it fixed earlier, but I got pulled onto other tasks. I believe the issue is that for 3-phase AC models when running on-design, the code runs with the specified design efficiency, but it calculates the impedance incorrectly. So when it subsequently runs off-design and uses that impedance to drive the losses, the breaker does not run with the same efficiency. I need to finish the branch I am working on to fix this though.

I hope to get the fix merged in by the end of this week, We very much appreciate your feedback and hope your master's thesis goes well.

Thanks,

George Thomas
NASA Glenn Research Center

**Comment by MoGeK** [comment] 2020-08-11 11:22
Thanks for the response George!

I am very much looking forward to the merged fix. The upcoming updates of the PSL will definitely be interesting.
I also really appreciate the work and effort you guys are putting into the project here on Github. It’s great to be able to interact with you and exchange ideas.
I will keep you updated, if I stumble upon other issues or anomalies!

Best regards,
Moritz

**Comment by georgelthomas** [comment] 2020-10-15 20:45
Hi Moritz,

Sorry for taking so long to get to this. I believe we have the issue fixed. The model should now run the same efficiency on-design and off-design. See the latest commit in master.

All the best,

George

**Closed as completed** 2020-10-30 19:15 UTC
